//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentRecord
    {
        public int EnrollmentID { get; set; }
        public int EnrollmentStudent { get; set; }
        public int EnrollmentCourse { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
